module.exports =  {
  sheetId: "1yTkGmIGFQHDsayHxFTgFIfdYxiaPQ6XUN5N-NtGzAlQ",
  sheetTitle: "Expenses",
  apiCredsPath: './finance-tracker-291520-ecef5232b18_creds.json',
  serviceNameConfigKey: 'schwab',
  schwab: {
    csvPath: './schwab.csv',
    headerNormalization: {
      'Date': 'Timestamp',
      'Type': 'Purchase Date',
      'Check #': 'Check #',
      Description: 'Item',
      'Withdrawal (-)': 'Amount',
      'Deposit (+)': 'Amount',
      RunningBalance: 'Category',
    },
    categorize: {
      'Interest Paid':	'Income',
      'ATM Fee Rebate':	'Income',
      'TRINET HR CORPOR PAYROLL 201031~ Tran: A':	'Income',
      'NAVI ED SERV WEB STUDNTLOAN 201019':	'Bills',
      'SQ *THE GLUTEN FREChatham NY #000000190':	'Dining',
      'TRINET HR CORPOR PAYROLL 201015~ Tran: A':	'Income',
      'TD BANK 2-4 FLATBUSH AV BROOKLYN':	'Bills',
      'PAYPAL INST XFER 201002':	'Subscriptions',
      'SQ *THE DOJO NYC  gosq.com NY #00000019':	'Subscriptions',
      'Cardtronics CCS 3823 NO BROOKLYN':	'Dining',
      'VENMO PAYMENT ~ Tran: ACHDW':	'Dining',
      'VENMO PAYMENT ~ Tran: ACHDW':	'Dining',
    }
  },
  capitalOne: {
    csvPath: './capital_one.csv',
    headerNormalization: {
      'Transaction Date': 'Timestamp',
      'Posted Date': 'Purchase Date',
      'Card No.': 'Card No.',
      Description: 'Item',
      Category: 'Category',
      Debit: 'Amount',
      Credit: 'Amount',
    },
    categorize: {
      'SUN BASKET': 'Groceries',
      'Payment/Credit': 'Disregard',
      'NINTENDO *AMERICAUS': 'Subscriptions',
      'WHOLEFDS FTG #10709': 'Groceries',
      'FULLSCRIPT* R652924040': 'Health Care',
      'TUNE UP WORLDWIDE FITNES': 'Other Services',
      SEAMLSSKAMISUSHI: 'Dining',
      'BH* BETTERHELP': 'Health Care',
      'NAME-CHEAP.COM': 'Subscriptions',
      "Trader Joe's": 'Groceries',
      'Thrive Market': 'Groceries',
      interest: 'Income',
      Paycheck: 'Income',
      Food: 'Groceries',
      'NINTENDO    *AMERICAUS': 'Subscriptions',
      'FULLSCRIPT* R037735406': 'Health Care',
      'NEW YORK STATE DMV': 'Other Services',
      SEAMLSSTACOMBIFORTGRE: 'Dining',
      'TKP KIT': 'Shopping',
      'GENOVA DIAGNOSTICS INC': 'Health Care',
      'PARSLEY HEALTH': 'Health Care',
      'FULLSCRIPT* R345686389': 'Health Care',
      'PAYPAL *SCANPANUSA': 'Shopping',
      'THRIVE MARKET': 'Groceries',
      'MUJI U.S.A. LIMITED': 'Shopping',
      SEAMLSSNAMASTE: 'Dining',
      SEAMLSSXOCHITLTAQUERI: 'Dining',
      SEAMLSSMAYATAQUERIAPR: 'Dining',
      'BC.HEY 4559541': 'Other Services',
      SEAMLSSTAQUERIAFORTGR: 'Dining',
      'REI.COM': 'Shopping',
      'Amazon web services': 'Other Services',
      'ATLANTIC TERMINAL  GAR': 'Shopping',
      'TARGET.COM  *': 'Shopping',
      'RIVERVIEW * RIVERVIEWF': 'Shopping',
      RAINSHOWER: 'Shopping',
      SEAMLSSPEQUENA: 'Dining',
      SEAMLSSNATIONALTHAIRE: 'Dining',
      'INTEREST CHARGE:PURCHASES': 'Bills',
      'FULLSCRIPT* R401861761': 'Health Care',
      'PAYPAL *GATORIREPAI EBAY': 'Shopping',
      SEAMLSSBOMBAYKABAB: 'Dining',
      SEAMLSSKULUSHKAT: 'Dining',
      'FULLSCRIPT* R426651569': 'Health Care',
      'UPCOUNSEL.COM': 'Other Services',
      WeWork: 'Other Services',
      'SQ *OOTOYA CHELSEA': 'Dining',
      'FULLSCRIPT* R447595655': 'Health Care',
      SEAMLSSPITASANDSTICKS: 'Dining',
      'FULLSCRIPT* R517927061': 'Health Care',
      'CHARLIE CAR RENTAL': 'Travel',
      'UBER   TRIP': 'Transport',
      'AIRBNB  HME8QSJ3RE': 'Travel',
      'AIRBNB  HMMBYTHMBP': 'Travel',
      'LYFT   *RIDE SUN 7AM': 'Transport',
      'NORDVPN SUBSCRIPTION': 'Subscriptions',
      'AMZN Mktp US*1W5GF5CQ3': 'Shopping',
      'WHOLEFDS FTG #10 292 AS BROOKLYN': 'Groceries',
      'FRESH GARDEN      BROOKLYN NY #00000019': 'Groceries',
      'Duane Reade STO 386 FUL BROOKLYN': 'Shopping',
      'BRANDED SALOON    BROOKLYN NY #00000019': 'Dining',
      'TST* WHITE TIGER  BROOKLYN NY #00000019': 'Dining',
      'THE CENTER FOR FICBROOKLYN NY #00000019': 'Shopping',
      'TST* TACOMBI - FORBROOKLYN NY #00000019': 'Dining',
      'Greenlight Bookstore Brooklyn': 'Shopping',
      'THELIQUORSTORE.COMBROOKLYN NY #00000019': 'Dining',
      'CITIBAN0087494 139 FLAT BROOKLYN': 'Bills',
      'TRINET HR CORPOR PAYROLL 200915~ Tran: A': 'Income',
      'TTHE GREENE GRAPE BROOKLYN NY #00000019': 'Dining',
      'VENMO PAYMENT': 'Dining',
      'GREENE GRAPE PROVIBROOKLYN NY #00000019': 'Groceries',
      'BEST BUY WINES ANDBROOKLYN NY #00000019': 'Dining',
      'MR MANGO          BROOKLYN NY #00000019': 'Groceries',
      'GREENE BITES      BROOKLYN NY #00000019': 'Groceries',
      'SQ *THE DOJO NYC  gosq.com NY #00000019': 'Subscriptions',
      'PAYPAL INST XFER 200902': 'Subscriptions',
      'Interest Paid': 'Income',
      'TRINET HR CORPOR PAYROLL 200831~ Tran: A': 'Income',
      'SHOPRITE GARNERVLLE S1 GARNERVILLE': 'Groceries',
      'MTA*METROCARD MACHINE NEW YORK': 'Transport',
      'NAVI ED SERV WEB STUDNTLOAN 200824': 'Bills',
      'VINO BUENO        BROOKLYN NY #00000019': 'Dining',
      'CVS/PHARMACY #02 02428- BROOKLYN': 'Shopping',
      'TRINET HR CORPOR PAYROLL 200815~ Tran: A': 'Income',
      'BROOKLYN FARE #192BROOKLYN NY #00000019': 'Groceries',
      'P191635 759 FULTON STRE BROOKLYN': 'Dining',
      'EVELINA RESTAURANT917-4495412 NY #00000': 'Dining',
      'TD BANK 2-4 FLATBUSH AV BROOKLYN': 'Bills',
      'KEYSTONE MANAGEMENBROOKLYN NY #00000019': 'Shopping',
      'JOHN SCOTTS SURF SWESTHAMPTON NY #00000': 'Dining',
      'PAYPAL INST XFER 200803': 'Subscriptions',
      'HENRI AT COOPER`S SOUTHAMPTON NY #00000': 'Groceries',
      'SCHMIDTS MARKET   SOUTHAMPTON NY #00000': 'Groceries',
      'HERBERT & RIST LIQSOUTHAMPTON NY #00000': 'Dining',
      'CVS/PHARMACY #05 05062- SOUTHAMPTON': 'Groceries',
      'ATM Fee Rebate': 'Income',
      'TRINET HR CORPOR PAYROLL 200731~ Tran: A': 'Income',
      'PAYPAL INST XFER 200729': 'Shopping',
      'NAVI ED SERV WEB STUDNTLOAN 200715': 'Bills',
      'TRINET HR CORPOR PAYROLL 200715~ Tran: A': 'Income',
      'WHOLEFDS USQ 10162NEW YORK NY #00000019': 'Groceries',
      'Extra Fancy Farm  Brooklyn NY #00000019': 'Groceries',
      'NAVI ED SERV WEB STUDNTLOAN 200703': 'Bills',
      'PAYPAL INST XFER 200704': 'Subscriptions',
      'TRINET HR CORPOR PAYROLL 200630~ Tran: A': 'Income',
      'DECICCO MARKETPLACJEFFERSON VAL NY #000': 'Groceries',
      'FAHNESTOCK SP     CARMEL NY #0000001900': 'Travel',
      'PAYPAL INST XFER 200621': 'Shopping',
      "GARDEL'S GREENE GABROOKLYN NY #00000019": 'Shopping',
      'TRINET HR CORPOR PAYROLL 200615~ Tran: A': 'Income',
      'PAYPAL INST XFER 200610': 'Shopping',
      'BANK OF AMERICA *FLATBU BROOKLYN': 'Bills',
      'MR MANGO 59 LAFAYETTE A BROOKLYN': 'Groceries',
      'PAYPAL INST XFER 200607': 'Shopping',
      'NAVI ED SERV WEB STUDNTLOAN 200529': 'Bills',
      'TRINET HR CORPOR PAYROLL 200531~ Tran: A': 'Income',
      'TRINET HR CORPOR PAYROLL 200515~ Tran: A': 'Income',
      'CITIBAN0087491 139 FLAT BROOKLYN': 'Bills',
      'PAYPAL INST XFER 200505': 'Subscriptions',
      'NAVI ED SERV WEB STUDNTLOAN 200430': 'Bills',
      'PAYPAL INST XFER 200430': 'Shopping',
      'TRINET HR CORPOR PAYROLL 200430~ Tran: A': 'Income',
      'IRS  TREAS 310 TAX REF 043020~ Tran: ACH': 'Income',
      'Check Paid #1082': 'Bills',
      'EXECUTE PROGRAM   EXECUTEPROGRA WA #000': 'Shopping',
      'TRINET HR CORPOR PAYROLL 200415~ Tran: A': 'Income',
      'JASON SANDERS LA SALE 200413': 'Bills',
      'PAYPAL INST XFER 200405': 'Subscriptions',
      'CITIBAN0087493 139 FLAT BROOKLYN': 'Bills',
      'TARGET T-1849 139 Flatb Brooklyn': 'Shopping',
      'GoFndMe* Dojo QuarRedwood City CA #0000': 'Gifts',
      'CHRISTOPHER DAOU SENDER 200401': 'Income',
      'ADP TOTALSOURCE DIRECT DEP 200319~ Tran:': 'Income',
      'SQ *DUNCANS FISH MBrooklyn NY #00000019': 'Groceries',
      'TAXI SVC LONG ISLALONG ISLAND C NY #000': 'Transport',
      'ETC               NEW YORK NY #00000019': 'Transport',
      'PAYPAL INST XFER 200306': 'Subscriptions',
      'TAXI SVC WOODSIDE WOODSIDE NY #00000019': 'Transport',
      'TAPINGOTAHENIGRILL8002561020 NY #000000': 'Dining',
      'ADP TOTALSOURCE DIRECT DEP 200305~ Tran:': 'Income',
      'PERELANDRA NATURAL FOOD BROOKLYN': 'Groceries',
      'Deposit Mobile Banking': 'Income',
      'CALEXICO CARNE ASABROOKLYN NY #00000019': 'Dining',
      'NAVI ED SERV WEB STUDNTLOAN 200224': 'Bills',
      'MOMA ADMISSION TICNEW YORK NY #00000019': 'Entertainment',
      'SQ *YELLOW BELL FABrooklyn NY #00000019': 'Shopping',
      'TST* OLEA         BROOKLYN NY #00000019': 'Dining',
      'ADP TOTALSOURCE DIRECT DEP 200220~ Tran:': 'Income',
      'DISCOVER E-PAYMENT 200206': 'Bills',
      'PAYPAL INST XFER 200205': 'Subscriptions',
      'ADP TOTALSOURCE DIRECT DEP 200206~ Tran:': 'Income',
      'VIENA SNACKS      CAROLINA    #00000019': 'Groceries',
      'EL MARKET PUERTO RCAROLINA    #00000019': 'Groceries',
      'DUFRY PUERTO RICO CAROLINA    #00000019': 'Gifts',
      'HTTP://WWW.GOGOAIR877-350-0038 IL #0000': 'Travel',
      'TOSTADO CALLE LOIZA 180 SAN JUAN': 'Dining',
      'PIZZA TO GO INC   LUQUILLO    #00000019': 'Dining',
      'BOARDRIDERS SURF BLUQUILLO    #00000019': 'Dining',
      'WAL-MART #3682 CALLE 2 LUQUILLO': 'Groceries',
      'SUPERMERCADOS PLAZSAN JUAN    #00000019': 'Groceries',
      'AZUCENA           SAN JUAN    #00000019': 'Dining',
      'SHARENET CALLE 1 & PR3 LUQUILLO': 'Travel',
      'NAVI ED SERV WEB STUDNTLOAN 200127': 'Bills',
      'TRESBE            SAN JUAN    #00000019': 'Dining',
      'DISCOVER E-PAYMENT 200124': 'Bills',
      'LEVIS BAR & GRILL EL AU SAN JUAN': 'Dining',
      'LIBROS AC LIBRERIA & B SAN JUAN': 'Shopping',
      'SUPERMAX DE DIEGO SAN JUAN    #00000019': 'Groceries',
      'KAMOLI BOUTIQUE   SAN JUAN    #00000019': 'Shopping',
      'ADP TOTALSOURCE DIRECT DEP 200123~ Tran:': 'Income',
      'TRADITION FRANCAISSAN JUAN    #00000019': 'Dining',
      '*  *CALLE LOIZA ESQ KIN SAN JUAN': 'Dining',
      'ACAPULCO RESTAURANT LOC SAN JUAN': 'Dining',
      'ARADO COCINA DE RAIZ 25 ARECIBO': 'Dining',
      'WALGREENS STORE 889 CAL LUQUILLO': 'Groceries',
      'LENAS CAFE 152 CALLE FE LUQUILLO': 'Dining',
      'Wal-Mart Super Center 3 LUQUILLO': 'Groceries',
      'PUEBLO ISLA VERDE CAROLINA    #00000019': 'Shopping',
      'HUMMUS INC        BROOKLYN NY #00000019': 'Groceries',
      'STARBUCKS B POST ENEWARK NJ #0000001900': 'Dining',
      'THE QUARTER       BROOKLYN NY #00000019': 'Dining',
      'DISCOVER E-PAYMENT 200110': 'Bills',
      "TRADER JOE'S #547 BROOKLYN NY #00000019": 'Groceries',
      'Cardtronics CCT EWR  TE NEWARK': 'Travel',
      'TST*GREGORYS COFFEBROOKLYN NY #00000019': 'Dining',
      'SQ *PARSLEY HEALTHNEW YORK NY #00000019': 'Shopping',
      'CHIPOTLE 0476     NEW YORK NY #00000019': 'Dining',
      'ADP TOTALSOURCE DIRECT DEP 200109~ Tran:': 'Income',
      'Duane Reade STO 37 BROA NEW YORK': 'Groceries',
      'PAYPAL INST XFER 200106': 'Subscriptions',
      'RADICLE HERB SHOP BROOKLYN NY #00000019': 'Shopping',
      'ADP TOTALSOURCE DIRECT DEP 200103~ Tran:': 'Income',
      'MASALA GRILL      BROOKLYN NY #00000019': 'Dining',
      'DISCOVER E-PAYMENT 191226': 'Bills',
      'ADP TOTALSOURCE DIRECT DEP 191227': 'Income',
      'ADP TOTALSOURCE DIRECT DEP 191226~ Tran:': 'Income',
      'MUJI CHELSEA 21241NEW YORK NY #00000019': 'Shopping',
      'CHIPOTLE 3309     BROOKLYN NY #00000019': 'Dining',
      "FREDDY'S FOOD MARKBROOKLYN NY #00000019": 'Dining',
      'BEST BUY WINES AND SPIR BROOKLYN': 'Dining',
      'DISCOVER E-PAYMENT 191216': 'Bills',
      'SP * 20 SIDED STORBROOKLYN NY #00000019': 'Shopping',
      'BLUE RIBBON SUSHI NEW YORK NY #00000019': 'Dining',
      'CVS/PHARMACY #10 10042- BROOKLYN': 'Shopping',
      'ADP TOTALSOURCE DIRECT DEP 191212~ Tran:': 'Income',
      'P417216 81 LAFAYETTE AV BROOKLYN': 'Dining',
      'CHRISTMASTREECLIN-NEW YORK NY #00000019': 'Gifts',
      'TURNTABLE LP BAR &NEW YORK NY #00000019': 'Dining',
      'PAYPAL INST XFER 191207': 'Subscriptions',
      'VENMO CASHOUT': 'Income',
      'MEKONG BK CORP    BROOKLYN NY #00000019': 'Dining',
      'PAYPAL INST XFER 191205': 'Shopping',
      'REBOUNDERZ WM     JENISON MI #000000190': 'Gifts',
      'GREENLIVINGST2637 DETROIT': 'Shopping',
      'PAYPAL INST XFER 191129': 'Shopping',
      'JIMMY JOHNS - 3321JENISON MI #000000190': 'Dining',
      'VICTORY LANE QUICKHOWELL MI #0000001900': 'Other Services',
      'MEIJER 226 ROCKFORD': 'Groceries',
      'DISCOVER E-PAYMENT 191127': 'Bills',
      'WHOLEFDS ARB 101 3315 W ANN ARBOR': 'Groceries',
      'COTTO MARKET      FLUSHING NY #00000019': 'Groceries',
      'ADP TOTALSOURCE DIRECT DEP 191127~ Tran:': 'Income',
      'GAP OUTLET US 7059BROOKLYN NY #00000019': 'Shopping',
      'NEW WONJO RESTAURANEW YORK NY #00000019': 'Dining',
      'PASSPORTSERVICES PAYMENT 191122 3711': 'Other Services',
      'FLYING TIGER COPENHAGE BROOKLYN': 'Gifts',
      'METRO INTEGRATIVE PHARM NEW YORK': 'Health Care',
      'USPS PO 35087703 539 AT BROOKLYN': 'Other Services',
      'DISCOVER E-PAYMENT 191116': 'Bills',
      'TST* BROOKLYN PUBLBROOKLYN NY #00000019': 'Shopping',
      'ADP TOTALSOURCE DIRECT DEP 191114~ Tran:': 'Income',
      'PAYPAL INST XFER 191110': 'Shopping',
      'PAI ISO 59 LAFFAYETTE BROOKLYN': 'Dining',
      'TST* WALTER S - FOBROOKLYN NY #00000019': 'Dining',
      'PAYPAL INST XFER 191107': 'Subscriptions',
      'TST* BLACK FOREST BROOKLYN NY #00000019': 'Dining',
      'Randolph Beer - DuBrooklyn NY #00000019': 'Dining',
      'ADP TOTALSOURCE DIRECT DEP 191031~ Tran:': 'Income',
      'THE GARDEN FOOD MABROOKLYN NY #00000019': 'Groceries',
      'MONK VINTAGE CORP 37 GR BROOKLYN': 'Shopping',
      'GARRYS WINE & LIQUBROOKLYN NY #00000019': 'Dining',
      'DISCOVER E-PAYMENT 191019': 'Bills',
      'HU KITCHEN        NEW YORK NY #00000019': 'Dining',
      'ADP TOTALSOURCE DIRECT DEP 191017~ Tran:': 'Income',
      'GREENPOINT NATURAL MRKT BROOKLYN': 'Groceries',
      'MARIAM            BROOKLYN NY #00000019': 'Dining',
      'UNIQLO ATLANTIC TEBROOKLYN NY #00000019': 'Shopping',
      'CVS/PHARMACY #10 10086- BROOKLYN': 'Shopping',
      'MASTERPIECE SMOKE AND V BROOKLYN': 'Shopping',
      'PAYPAL INST XFER 191008': 'Subscriptions',
      'KICOPI            BROOKLYN NY #00000019': 'Shopping',
      'DISCOVER E-PAYMENT 191006': 'Bills',
      'GOLDEN YEARS      BROOKLYN NY #00000019': 'Shopping',
      'CHASE 20 FLATBUSH AVE BROOKLYN': 'Bills',
      'LEAN CRUST CORP 737 FUL BROOKLYN': 'Dining',
      'W273172 727 FULTON STRE BROOKLYN': 'Shopping',
      'ADP TOTALSOURCE DIRECT DEP 191003~ Tran:': 'Income',
      'MTA*MNR STATION TIX NEW YORK': 'Transport',
      'NATIONAL          BROOKLYN NY #00000019': 'Dining'
    }
  },
  // capitalOneHeaders: {
  //   'Transaction Date': 'Timestamp',
  //   'Posted Date': 'Purchase Date',
  //   'Card No.': 'Card No.',
  //   Description: 'Item',
  //   Category: 'Category',
  //   Debit: 'Amount',
  //   Credit: 'Amount',
  // },
  // schwabHeaders: {
  //   'Date': 'Timestamp',
  //   'Type': 'Type',
  //   'Check #': 'Check #',
  //   Description: 'Item',
  //   'Withdrawal (-)': 'Amount',
  //   'Deposit (+)': 'Amount',
  //   RunningBalance: 'Category',
  // },
}